name: Deploy

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set-up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish
        run: |
          yarn install --frozen-lockfile --ignore-scripts --prefer-offline
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Extract the release body from CHANGELOG.md
        id: changelog
        shell: bash
        run: |
          node ./scripts/extract_last_release_body.js
          RELEASE=$(cat ./RELEASE.md)
          echo "RELEASE_BODY=$RELEASE" >> $GITHUB_OUTPUT
      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./index.js
          asset_name: postcss-rtlcss.js
          tag: ${{ github.ref }}
          body: |
            ${{ steps.changelog.outputs.RELEASE_BODY }}
          overwrite: true